### ISSUE TITLE
Incompatible with `libalpm.so.16`

### ISSUE THREAD

**Issue by es20490446e** [manjaro/libpamac#6]
```
src/dependency-checker.p/alpm_config.c:957:9: error: implicit declaration of function ‘alpm_option_set_disable_sandbox’; did you mean ‘alpm_option_set_disable_sandbox_syscalls’? [-Wimplicit-function-declaration]
src/outdated-checker.p/alpm_config.c:957:9: error: implicit declaration of function ‘alpm_option_set_disable_sandbox’; did you mean ‘alpm_option_set_disable_sandbox_syscalls’? [-Wimplicit-function-declaration]
src/libpamac-aur.so.11.7.p/alpm_config.c:947:9: error: implicit declaration of function ‘alpm_option_set_disable_sandbox’; did you mean ‘alpm_option_set_disable_sandbox_syscalls’? [-Wimplicit-function-declaration]
```

Due to [undocumented API change](https://gitlab.archlinux.org/pacman/pacman/-/issues/285).

**Comment by yochananmarqos** [comment]
As I'm sure you already know, Pacman 7.1.0 is not yet available in any repo--not even Arch core-staging.

Either way, please provide more information about what commands you're running.

**Comment by es20490446e** [comment]
I know, but the bug is coming.
```
local Build="${srcdir}/_build"
arch-meson --reconfigure "${pkgname}" "${Build}"
so meson compile -C "${Build}"
```

**Comment by yochananmarqos** [comment]
Sorry, please try again. That's not a log. C'mon, Alberto. I know you know better.

**Comment by yochananmarqos** [comment]
Linking your Pacman issue here for reference: https://gitlab.archlinux.org/pacman/pacman/-/issues/285

**Comment by yochananmarqos** [comment]
@es20490446e Since Allan addressed the issue upstream, I'm going to close this for now. Please feel free to reopen it or create a new issue when Pacman 7.1.0 is actually in the repositories.

**Comment by es20490446e** [comment]
Oki 👍

**Comment by G4Zz0L1** [comment]
EDIT: scratch that, wrong issue.

**Comment by yochananmarqos** [comment]
Addressed with add94a8.

**Comment by es20490446e** [comment]
Does this mean that the upstream fix is ineffective?

I have tried with the patched upstream pacman, but the fail is still present.

I know pacman is patched for sure because the soname is dumped, as the patch sets.

**Comment by yochananmarqos** [comment]
@es20490446e I just meant as far as libalpm 16 compatibility. Was the issue not fixed upstream? 

At this point, please create a new issue with detailed information since both this one and the pacman issue are closed.

**Comment by es20490446e** [comment]
The [commit in pacman](https://gitlab.archlinux.org/pacman/pacman/-/merge_requests/320) adds back `alpm_option_get_disable_sandbox`.

But the [commit in libpamac](https://github.com/manjaro/libpamac/commit/add94a888180ddbe04acae082e9db5cfb34c2fcd) sustitutes it for `alpm_option_get_disable_sandbox_filesystem` and `alpm_option_get_disable_sandbox_syscalls`.

If I have `pacman` with that commit, but `libpamac` without the second, it fails to build.

---

To fix this issue you need:

1. To reopen this report.
2. Test if the provided info is true.
3. If so, report yourself upstream.
4. Close this report.

**Comment by yochananmarqos** [comment]
Upstream replaced DisableSandbox with both DisableSandboxFilesystem and DisableSandboxSyscalls. Have you checked your pacnews?

**Comment by es20490446e** [comment]
Yes!!

Read the [pacman commit](https://gitlab.archlinux.org/pacman/pacman/-/merge_requests/320) I have provided.

**Comment by yochananmarqos** [comment]
@es20490446e To be clear, I'm just doing my best with helping Guillaume out with issues here. 

As far as I can tell, both Allan and Guillaume already addressed the issue. Unless you can provide more information, this is going nowhere.

Again, since this issue has been addressed and is closed, please create a new issue with new information based on the new changes. Feel free to reference this issue.

**Comment by hphilm** [comment]
First of all @es20490446e is correct. Current **libpamac** is not supporting **libalpm 16.0.1** which readds `alpm_option_set_disable_sandbox()` to the code. @guinux needs to adopt that aswell. 

See https://gitlab.archlinux.org/pacman/pacman/-/commit/63bfb53afcb9bb09a4a0aa64b6a29a479fc854f0 in 7.1.x branch of pacman repo.

**Comment by guinux** [comment]
Did you try to build libpamac against libalpm 16.0.1 ? No problem on my side, Alan readded `alpm_option_set_disable_sandbox()`  function but kept the other ones.

**Comment by es20490446e** [comment]
If I build the unpatched libpamac with the patched pacman, the build fails.

Which means the pacman patch doesn't work.

**Comment by hphilm** [comment]
For now I reverted the addition to make it work https://gitlab.manjaro.org/packages/core/pacman/-/commit/0120ae67cc4f71006dd19b6900ee63f879070a67

**Comment by hphilm** [comment]
Seems the revert on pacman was not needed. On Manjaro we compile libpamac with https://github.com/manjaro/libpamac/commit/add94a888180ddbe04acae082e9db5cfb34c2fcd included to make it work. @es20490446e did you tried that yet?

**Comment by es20490446e** [comment]
@hphilm What I'm trying to say is that the [patch on pacman](https://gitlab.archlinux.org/pacman/pacman/-/merge_requests/320) seems not to work, otherwise the [patch on libpamac](https://github.com/manjaro/libpamac/commit/add94a888180ddbe04acae082e9db5cfb34c2fcd) won't be needed.

That instead of patching libpamac, we shall report upstream that their fix isn't working.

**Comment by squid-f** [comment]
Hi. Not sure who should update its package, but here is what I get while trying to update:
```
$ paru -S libpamac-aur
:: Résolution des dépendances...
:: Calcul des conflits...
:: Calcul des conflits internes...

Dépôt (2)                Ancienne Version     Nouvelle Version     Make Only
core/libmakepkg-dropins                       18-1                 Non
core/pacman              7.0.0.r6.gc685ae6-6  7.1.0.r7.gb9f7d4a-1  Non

Aur (1)                  Ancienne Version     Nouvelle Version     Make Only
aur/libpamac-aur         11.7.4-1             11.7.4-2             Non

:: Procéder à la relecture ? [O/n]

:: Téléchargement des PKGBUILDs...
PKGBUILDs à jour
Paging with less. Press 'q' to quit or 'h' for help.

:: libpamac-aur:
.gitignore:
*.zip
*.gz
*.tar
*.tar.*
/pkg/*
/src/*

fix-appstream-data.hook:
[Trigger]
Operation = Install
Operation = Upgrade
Type = Path
Target = usr/share/swcatalog/xmls/*.xml.gz

# attention: hook name before: update-appstream-cache.hook

[Action]
Description = fix appstream datas for pamac
When = PostTransaction
Depends = gzip
Exec = /etc/pacman.d/hooks.bin/fix-appstream-data.sh
NeedsTargets

:: Accepter les changements ? [O/n]
résolution des dépendances…
recherche des conflits entre paquets…
erreur : la préparation de la transaction a échoué (la satisfaction des dépendances a échoué)
:: l’installation de pacman (7.1.0.r7.gb9f7d4a-1) casse la dépendance « libalpm.so=15 » requise par libpamac-aur
```

In short and in english: "pacman (7.1.0.r7.gb9f7d4a-1) breaks dependency to « libalpm.so=15 » required by libpamac-aur

I am on Garuda Linux (Arch based).

**EDIT: I uninstall any pamac related packages and installed from AUR `pamac-aur 11.7.4-2`
Everything works again... sorry for the noise.**

**Comment by hphilm** [comment]
@squid-f **libpamac** needs add94a888180ddbe04acae082e9db5cfb34c2fcd to work with libalpm 16 or 16.0.1. New functions got added by the API bump.

@es20490446e feel free to report upstream, but for now add94a888180ddbe04acae082e9db5cfb34c2fcd is needed in libpamac to work with pacman 7.1 releases. Did you actually test both patched to see if there are any regressions?

**Comment by es20490446e** [comment]
I tested the pacman patch. With libpamac I just used:

```
sed \
    's|alpm_option_set_disable_sandbox"|alpm_option_set_disable_sandbox_syscalls"|' \
    --in-place "${srcdir}/${pkgname}/vapi/libalpm.vapi"
```

To truly fix this issue, you need to test it yourselves and report it upstream if needed.
